import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Routes, Route, Link, NavLink, Navigate, Outlet, useLocation, useNavigate, useOutletContext, useParams, useSearchParams } from 'react-router-dom';
import { upload } from '@vercel/blob/client';
import '@fontsource/outfit/latin-400.css';
import '@fontsource/outfit/latin-500.css';
import '@fontsource/outfit/latin-600.css';
import '@fontsource/fraunces/latin-400.css';
import { api } from './api.js';
import './styles.css';

const categories = ['Bread', 'Pastries', 'Cakes', 'Drinks'];
const samplePhotos = { Bread: '/images/sample-bakery-hero.webp', Pastries: '/images/sample-pastries.webp', Cakes: '/images/sample-cakes.webp', Drinks: '/images/sample-drinks.webp' };
const money = value => `${Number(value).toLocaleString()} sample units`;
const dateLabel = (value, zone = 'Africa/Cairo') => new Intl.DateTimeFormat(undefined, { dateStyle: 'full', timeZone: zone }).format(new Date(value));
const timeLabel = (value, zone = 'Africa/Cairo') => new Intl.DateTimeFormat(undefined, { hour: 'numeric', minute: '2-digit', timeZone: zone }).format(new Date(value));
function Notice({ children, error = false }) { return <p className="notice" role={error ? 'alert' : 'status'}>{children}</p>; }
function RequestError({ error, retry }) { return <section className="state-panel"><h1>We couldn’t load this page.</h1><p>{error || 'The service is unavailable. Your cart is still saved for this browser session.'}</p><button onClick={retry}>Try again</button></section>; }
function RouteFocus() { const { pathname } = useLocation(); useEffect(() => { document.querySelector('main')?.focus(); window.scrollTo(0, 0); }, [pathname]); return null; }
function CustomerShell() {
  const location = useLocation();
  const [ready, setReady] = useState(false); const [error, setError] = useState(''); const [retry, setRetry] = useState(0); const [cartCount, setCartCount] = useState(0);
  const refreshCart = async () => { const data = await api('/cart'); setCartCount(data.items.reduce((sum, item) => sum + item.quantity, 0)); };
  useEffect(() => { let active = true; setReady(false); setError(''); api('/customer/session').then(() => api('/cart')).then(data => { if (active) { setCartCount(data.items.reduce((sum, item) => sum + item.quantity, 0)); setReady(true); } }).catch(failure => { if (active) setError(failure.message); }); return () => { active = false; }; }, [retry]);
  useEffect(() => { const update = () => refreshCart().catch(() => {}); window.addEventListener('cart-updated', update); return () => window.removeEventListener('cart-updated', update); }, []);
  useEffect(() => { if (ready) document.getElementById('main')?.focus(); }, [ready, location.pathname]);
  if (!ready) return <main className="page">{error ? <RequestError error={error} retry={() => setRetry(n => n + 1)}/> : <Notice>Opening your session cart…</Notice>}</main>;
  return <><a className="skip" href="#main">Skip to content</a><div className="announcement">Pickup daily, 8:00 a.m. to noon <span>·</span> Pay at pickup</div><header className="header"><Link className="wordmark" to="/">[Bakery name]<small>Sample brand</small></Link><nav aria-label="Storefront"><div className="category-nav">{categories.map(category => <Link key={category} to={`/?category=${encodeURIComponent(category)}`}>{category}</Link>)}</div><Link className="cart-link" to="/cart">Cart <span aria-label={`${cartCount} items in cart`}>{cartCount}</span></Link></nav></header><main id="main" tabIndex="-1"><Outlet context={{ cartCount, refreshCart }}/></main><footer><span>Daily pickup · 8:00 a.m. to noon · Pay at pickup</span><Link to="/owner/login">Owner sign in</Link></footer></>;
}
function Catalog() {
  const [searchParams, setSearchParams] = useSearchParams(); const location = useLocation();
  const category = searchParams.get('category') || ''; const query = searchParams.get('search') || '';
  const [input, setInput] = useState(query); const [state, setState] = useState({ loading: true });
  useEffect(() => setInput(query), [query]);
  useEffect(() => { let active = true; setState({ loading: true }); const params = new URLSearchParams(); if (category) params.set('category', category); if (query) params.set('search', query); api(`/products${params.size ? `?${params}` : ''}`).then(data => { if (active) setState({ products: data.products }); }).catch(error => { if (active) setState({ error }); }); return () => { active = false; }; }, [category, query]);
  const chooseCategory = value => { const next = new URLSearchParams(searchParams); value ? next.set('category', value) : next.delete('category'); setSearchParams(next); };
  return <section className="catalog-page">
    <div className="hero"><div className="hero-copy"><p className="eyebrow">A neighborhood bakery · Sample storefront</p><h1>Good things,<br/>fresh from the oven.</h1><p>Browse sample listings, choose a pickup time, and pay when you arrive.</p><a className="button" href="#menu">Explore the menu</a><span className="sample-note">Illustrative content · bakery details pending</span></div><div className="hero-image"><img src="/images/sample-bakery-hero.webp" alt="Illustrative sample photograph of bread and pastries on a sunlit counter"/><span>Illustrative sample photo</span></div></div>
    <section id="menu" className="menu"><div className="section-heading"><div><p className="eyebrow">The menu</p><h2>Made for today</h2></div><p className="price-note">Prices are sample units; currency is unconfirmed.</p></div>
      <form className="search" onSubmit={event => { event.preventDefault(); const next = new URLSearchParams(searchParams); input.trim() ? next.set('search', input.trim()) : next.delete('search'); setSearchParams(next); }}><label htmlFor="product-search">Search products</label><div><input id="product-search" type="search" value={input} onChange={event => setInput(event.target.value)} placeholder="Try bread or pastry"/><button type="submit">Search</button></div></form>
      <div className="filter-row" aria-label="Filter by category"><button className={!category ? 'filter active' : 'filter'} aria-pressed={!category} onClick={() => chooseCategory('')}>All items</button>{categories.map(item => <button key={item} className={category === item ? 'filter active' : 'filter'} aria-pressed={category === item} onClick={() => chooseCategory(item)}>{item}</button>)}</div>
      <p className="sr-only" aria-live="polite">{state.products?.length ?? 0} products found</p>
      {state.loading ? <div className="state-panel"><p>Loading the menu…</p></div> : state.error ? <RequestError error={state.error.message} retry={() => setSearchParams(new URLSearchParams(searchParams))}/> : !state.products.length ? <div className="state-panel"><h3>{query ? 'No matches yet' : 'Nothing in this category yet'}</h3><p>Try another search or browse all sample products.</p><button className="secondary" onClick={() => { setInput(''); setSearchParams({}); }}>Show all items</button></div> : <div className="product-grid">{state.products.map((product, index) => <ProductCard key={product._id} product={product} featured={index === 0 && !category && !query}/>)}</div>}
    </section></section>;
}
function ProductPhoto({ product, className = '' }) { const [failed, setFailed] = useState(false); const fallback = !product.imageUrl || failed; const label = product.sample && fallback ? 'Sample listing · illustrative photo' : product.sample ? 'Sample listing' : fallback ? 'Illustrative sample photo' : ''; return <div className={`product-photo ${className}`}><img src={fallback ? samplePhotos[product.category] || samplePhotos.Bread : product.imageUrl} alt={fallback ? `Illustrative sample ${product.category.toLowerCase()} photo; product photography is unconfirmed` : product.name} loading="lazy" onError={() => setFailed(true)}/>{label && <small>{label}</small>}</div>; }
function ProductCard({ product, featured }) {
  const location = useLocation(); const [added, setAdded] = useState(false); const [error, setError] = useState('');
  async function add(event) { event.preventDefault(); setError(''); setAdded(false); try { await api('/cart/items', { method: 'POST', body: { productId: product._id, quantity: 1 } }); setAdded(true); window.dispatchEvent(new Event('cart-updated')); setTimeout(() => setAdded(false), 1800); } catch (failure) { setError(failure.message); } }
  return <article className={`product-card ${featured ? 'featured' : ''}`}><Link to={`/products/${product._id}?from=${encodeURIComponent(location.pathname + location.search)}`}><ProductPhoto product={product}/><div className="product-info"><div className="product-title"><h3>{product.name}</h3><span>{money(product.price)}</span></div><p>{product.description}</p><span className={product.stock ? 'stock' : 'stock sold'}>{product.stock ? `${product.stock} available` : 'Sold out'}</span></div></Link><div className="card-action"><button disabled={!product.stock} onClick={add}>{!product.stock ? 'Sold out' : added ? 'Added to cart' : 'Add to cart'}</button>{error && <span role="alert">{error}</span>}<span className="sr-only" role="status" aria-live="polite">{added ? `${product.name} added to cart` : ''}</span></div></article>;
}
function ProductDetail() {
  const { productId } = useParams(); const location = useLocation(); const [product, setProduct] = useState(null); const [error, setError] = useState(''); const [retry, setRetry] = useState(0); const [quantity, setQuantity] = useState(1); const [message, setMessage] = useState('');
  useEffect(() => { let active = true; setProduct(null); setError(''); api(`/products/${productId}`).then(data => { if (active) setProduct(data.product); }).catch(failure => { if (active) setError(failure.message); }); return () => { active = false; }; }, [productId, retry]);
  async function add() { setMessage(''); try { await api('/cart/items', { method: 'POST', body: { productId, quantity } }); setMessage(`${quantity} added to your cart.`); window.dispatchEvent(new Event('cart-updated')); } catch (failure) { setMessage(failure.message); } }
  if (error) return error.includes('not available') ? <NotFound/> : <div className="page"><RequestError error={error} retry={() => setRetry(n => n + 1)}/></div>;
  if (!product) return <div className="page"><Notice>Loading product…</Notice></div>;
  const requestedPath = new URLSearchParams(location.search).get('from') || '/';
  const backUrl = new URL(requestedPath, window.location.origin);
  const catalogPath = backUrl.origin === window.location.origin && backUrl.pathname === '/' ? `${backUrl.pathname}${backUrl.search}` : '/';
  return <section className="page detail"><Link className="back-link" to={catalogPath}>Back to menu</Link><div className="detail-layout"><ProductPhoto product={product}/><div><p className="eyebrow">{product.category}{product.sample ? ' · Sample listing' : ''}</p><h1>{product.name}</h1><p>{product.description}</p><p className="price-large">{money(product.price)}</p><p className={product.stock ? 'stock' : 'stock sold'}>{product.stock ? `${product.stock} available` : 'Sold out'}</p><label htmlFor="quantity">Quantity</label><div className="quantity"><button className="secondary" aria-label="Decrease quantity" disabled={quantity <= 1} onClick={() => setQuantity(n => n - 1)}>−</button><input id="quantity" type="number" min="1" step="1" max={product.stock} value={quantity} onChange={event => setQuantity(Math.max(1, Number(event.target.value) || 1))}/><button className="secondary" aria-label="Increase quantity" disabled={quantity >= product.stock} onClick={() => setQuantity(n => n + 1)}>+</button></div><button disabled={!product.stock || quantity > product.stock} onClick={add}>Add to cart</button>{message && <Notice error={message.includes('available')}>{message}</Notice>}</div></div></section>;
}
function CartPage() {
  const [state, setState] = useState({ loading: true }); const [retry, setRetry] = useState(0); const [error, setError] = useState('');
  const load = () => api('/cart').then(data => setState(data)).catch(failure => setState({ error: failure.message }));
  useEffect(() => { load(); }, [retry]);
  async function update(id, quantity) { setError(''); try { if (quantity < 1) await api(`/cart/items/${id}`, { method: 'DELETE' }); else await api(`/cart/items/${id}`, { method: 'PATCH', body: { quantity } }); await load(); window.dispatchEvent(new Event('cart-updated')); } catch (failure) { setError(failure.message); await load(); } }
  if (state.error) return <div className="page"><RequestError error={state.error} retry={() => setRetry(n => n + 1)}/></div>;
  if (state.loading) return <div className="page"><Notice>Loading your cart…</Notice></div>;
  return <section className="page"><p className="eyebrow">Your session cart</p><h1>Your cart</h1>{error && <Notice error>{error}</Notice>}{!state.items.length ? <div className="state-panel"><h2>Your cart is empty</h2><p>Browse the sample menu and add something for pickup.</p><Link className="button" to="/">Browse the menu</Link></div> : <><div className="cart-lines">{state.items.map(({ productId, product, quantity, available }) => <article className="cart-line" key={productId}><div className="cart-product">{product ? <ProductPhoto product={product}/> : <div className="product-photo">Unavailable item</div>}<div><h2>{product?.name || 'Unavailable product'}</h2><p>{product ? money(product.price) : 'No longer listed'}</p>{!available && <Notice error>Availability changed. Update or remove this item.</Notice>}</div></div><div className="cart-controls"><button className="secondary" aria-label={`Remove one ${product?.name || 'item'}`} onClick={() => update(productId, quantity - 1)}>−</button><span>{quantity}</span><button className="secondary" aria-label={`Add one ${product?.name || 'item'}`} disabled={!product || quantity >= product.stock} onClick={() => update(productId, quantity + 1)}>+</button><strong>{product ? money(product.price * quantity) : '—'}</strong><button className="text-button" onClick={() => update(productId, 0)}>Remove</button></div></article>)}</div><div className="cart-summary"><p>Subtotal <strong>{money(state.total)}</strong></p><p>Pay at pickup · sample prices</p><div><Link className="button secondary" to="/">Continue shopping</Link><Link className="button" aria-disabled={state.items.some(item => !item.available)} to={state.items.some(item => !item.available) ? '/cart' : '/checkout'}>Continue to pickup</Link></div></div></>}</section>;
}
function Checkout() {
  const navigate = useNavigate(); const [dates, setDates] = useState(null); const [day, setDay] = useState('today'); const [slots, setSlots] = useState([]); const [slot, setSlot] = useState(''); const [cart, setCart] = useState(null); const [error, setError] = useState(''); const [pending, setPending] = useState(false); const key = useRef(crypto.randomUUID());
  useEffect(() => { let active = true; Promise.all([api('/pickup-slots'), api('/cart')]).then(([availability, currentCart]) => { if (active) { setDates(availability.dates); setCart(currentCart); } }).catch(failure => { if (active) setError(failure.message); }); return () => { active = false; }; }, []);
  useEffect(() => { if (!dates) return; let active = true; setError(''); setSlots([]); setSlot(''); api(`/pickup-slots?date=${day}`).then(data => { if (active) setSlots(data.slots); }).catch(failure => { if (active) setError(failure.message); }); return () => { active = false; }; }, [dates, day]);
  async function submit(event) { event.preventDefault(); if (pending) return; const form = new FormData(event.currentTarget); setPending(true); setError(''); try { const data = await api('/orders', { method: 'POST', body: { customerName: form.get('name'), phone: form.get('phone'), pickupAt: slot, idempotencyKey: key.current } }); window.dispatchEvent(new Event('cart-updated')); navigate(`/orders/${encodeURIComponent(data.order.orderNumber)}/confirmation`, { replace: true }); } catch (failure) { setError(failure.message); if (failure.code === 'INSUFFICIENT_STOCK') { const refreshed = await api('/cart').catch(() => null); if (refreshed) setCart(refreshed); } } finally { setPending(false); } }
  if (error && !cart) return <div className="page"><RequestError error={error} retry={() => window.location.reload()}/></div>;
  if (cart && !cart.items.length) return <section className="page"><h1>Your cart is empty</h1><p>Add products before checkout.</p><Link className="button" to="/">Browse the menu</Link></section>;
  return <section className="page checkout"><p className="eyebrow">Guest checkout</p><h1>Choose your pickup</h1><p>No account or online payment. Pay when you pick up your order.</p>{error && <Notice error>{error}{error.includes('available') && <Link to="/cart"> Review your cart.</Link>}</Notice>}<form onSubmit={submit} aria-busy={pending}><div className="checkout-form"><div className="form-section"><h2>Your details</h2><label htmlFor="customer-name">Name</label><input id="customer-name" name="name" autoComplete="name" required maxLength="120"/><label htmlFor="customer-phone">Phone number</label><input id="customer-phone" name="phone" type="tel" autoComplete="tel" required minLength="7" maxLength="24" pattern="\+?[0-9 ()-]{7,24}"/><h2>Pickup day</h2><div className="choice-row">{['today', 'tomorrow'].map(value => <label className="choice" key={value}><input type="radio" name="day" checked={day === value} onChange={() => setDay(value)}/><span>{value === 'today' ? 'Today' : 'Tomorrow'}<small>{dates?.[value]}</small></span></label>)}</div><h2>Pickup time</h2>{slots.length ? <div className="slot-grid">{slots.map(item => <label className="slot" key={item.pickupAt}><input type="radio" name="pickup" value={item.pickupAt} checked={slot === item.pickupAt} onChange={() => setSlot(item.pickupAt)}/><span>{item.label}</span></label>)}</div> : <Notice>No pickup times remain for this day. Choose another day.</Notice>}</div><aside className="summary-panel"><h2>Order summary</h2>{cart?.items.map(item => <p key={item.product?._id}>{item.quantity} × {item.product?.name || 'Unavailable item'} <strong>{money((item.product?.price || 0) * item.quantity)}</strong></p>)}<p className="total">Total due at pickup <strong>{money(cart?.total || 0)}</strong></p><p>Pay in person at pickup. Currency is unconfirmed; prices are sample units.</p><button type="submit" disabled={!slot || pending || cart?.items.some(item => !item.available)}>{pending ? 'Placing order…' : 'Place order'}</button><Link className="text-link" to="/cart">Back to cart</Link></aside></div></form></section>;
}
function Confirmation() {
  const { orderNumber } = useParams(); const [result, setResult] = useState(null); const [error, setError] = useState(''); const [pending, setPending] = useState(false); const [retry, setRetry] = useState(0);
  useEffect(() => { let active = true; api(`/orders/${encodeURIComponent(orderNumber)}`).then(data => { if (active) setResult(data); }).catch(failure => { if (active) setError(failure.message); }); return () => { active = false; }; }, [orderNumber, retry]);
  async function cancel() { setPending(true); setError(''); try { const data = await api(`/orders/${encodeURIComponent(orderNumber)}/cancel`, { method: 'POST' }); setResult(current => ({ ...current, order: data.order })); } catch (failure) { setError(failure.message); } finally { setPending(false); } }
  if (error && !result) return <section className="page"><RequestError error="This confirmation is only available in the browser session that placed the order." retry={() => setRetry(n => n + 1)}/></section>;
  if (!result) return <div className="page"><Notice>Loading your confirmation…</Notice></div>;
  const { order, cancellationCutoff } = result; const cancellable = ['New', 'Ready'].includes(order.status) && Date.now() <= new Date(cancellationCutoff).getTime();
  return <section className="page confirmation"><p className="success-mark" aria-hidden="true">✓</p><p className="eyebrow">Order placed</p><h1>We’ll see you at pickup.</h1><p>Your order number is <strong>{order.orderNumber}</strong></p>{error && <Notice error>{error}</Notice>}<div className="confirmation-panel"><h2>Pickup details</h2><p>{order.customerName} · {order.phone}</p><p>{dateLabel(order.pickupAt, result.timezone)} at {timeLabel(order.pickupAt, result.timezone)}</p><p className="price-large">{money(order.total)} due at pickup</p><p>Pay in person when you collect your order.</p><h2>Your items</h2>{order.items.map(item => <p key={item.productId}>{item.quantity} × {item.name} <strong>{money(item.unitPrice * item.quantity)}</strong></p>)}{order.status === 'Cancelled' ? <Notice>Your order is cancelled. The item quantities have been restored to stock.</Notice> : cancellable ? <div className="cancel-area"><p>Cancel by {dateLabel(cancellationCutoff, result.timezone)} at {timeLabel(cancellationCutoff, result.timezone)} if your plans change.</p><button className="secondary" disabled={pending} onClick={cancel}>{pending ? 'Cancelling…' : 'Cancel order'}</button></div> : <Notice>Cancellation is closed for this order.</Notice>}</div><Link className="button" to="/">Back to the menu</Link></section>;
}
function NotFound() { return <section className="page state-panel"><h1>That page isn’t here.</h1><p>Return to the menu to keep browsing.</p><Link className="button" to="/">Back to the menu</Link></section>; }

function SignIn() {
  const navigate = useNavigate(); const location = useLocation(); const [show, setShow] = useState(false); const [pending, setPending] = useState(false); const [error, setError] = useState('');
  async function submit(event) { event.preventDefault(); if (pending) return; const form = new FormData(event.currentTarget); setPending(true); setError(''); try { await api('/owner/session', { method: 'POST', body: { email: form.get('email'), password: form.get('password') } }); navigate('/owner/orders', { replace: true }); } catch (failure) { setError(failure.message); } finally { setPending(false); } }
  return <div className="login-page"><Link className="back-link" to="/">Back to storefront</Link><section className="login-panel"><p className="eyebrow">Owner area</p><h1>Sign in</h1><p>Manage sample listings and pickup orders.</p>{location.state?.expired && <Notice>Your session has expired. Sign in again.</Notice>}<form onSubmit={submit} aria-busy={pending}><label htmlFor="email">Email address</label><input id="email" name="email" type="email" autoComplete="username" required maxLength="254"/><label htmlFor="password">Password</label><div className="password"><input id="password" name="password" type={show ? 'text' : 'password'} autoComplete="current-password" required maxLength="256"/><button type="button" className="secondary" aria-controls="password" aria-pressed={show} onClick={() => setShow(!show)}>{show ? 'Hide' : 'Show'} password</button></div>{error && <Notice error>{error}</Notice>}<button type="submit" disabled={pending}>{pending ? 'Signing in…' : 'Sign in'}</button></form><p className="fine">Private owner access.</p></section></div>;
}
function OwnerShell() {
  const location = useLocation(); const navigate = useNavigate(); const [state, setState] = useState({ loading: true }); const [retry, setRetry] = useState(0); const [pending, setPending] = useState(false); const [notice, setNotice] = useState('');
  useEffect(() => { let active = true; setState({ loading: true }); api('/owner/session').then(data => { if (active) setState({ owner: data.owner }); }).catch(error => { if (active) setState({ error }); }); return () => { active = false; }; }, [location.pathname, retry]);
  useEffect(() => { if (state.owner) document.getElementById('main')?.focus(); }, [state.owner]);
  async function signOut() { setPending(true); setNotice(''); try { await api('/owner/session', { method: 'DELETE' }); navigate('/owner/login', { replace: true }); } catch (error) { if (error.status === 401) navigate('/owner/login', { replace: true }); else setNotice(error.message); } finally { setPending(false); } }
  if (state.loading) return <main className="page"><Notice>Checking owner access…</Notice></main>;
  if (state.error?.status === 401) return <Navigate to="/owner/login" replace state={{ expired: true }}/>;
  if (state.error) return <main className="page"><RequestError error={state.error.message} retry={() => setRetry(n => n + 1)}/></main>;
  return <><a className="skip" href="#main">Skip to content</a><header className="header owner-header"><Link className="wordmark" to="/owner/orders">[Bakery name]<small>Owner workspace</small></Link><nav aria-label="Owner"><NavLink to="/owner/orders">Orders</NavLink><NavLink to="/owner/products">Products</NavLink><button className="secondary" disabled={pending} onClick={signOut}>{pending ? 'Signing out…' : 'Sign out'}</button></nav></header>{notice && <Notice error>{notice}</Notice>}<main id="main" tabIndex="-1"><Outlet/></main></>;
}
function OwnerOrders() {
  const [searchParams, setSearchParams] = useSearchParams(); const archived = searchParams.get('view') === 'archived'; const [state, setState] = useState({ loading: true }); const [retry, setRetry] = useState(0); const [pendingId, setPendingId] = useState(''); const [actionNotice, setActionNotice] = useState('');
  useEffect(() => { let active = true; setState({ loading: true }); api(`/owner/orders?view=${archived ? 'archived' : 'recent'}`).then(data => { if (active) setState({ orders: data.orders, timezone: data.timezone }); }).catch(error => { if (active) setState({ error }); }); return () => { active = false; }; }, [archived, retry]);
  async function advance(order, status) { setPendingId(order._id); setActionNotice(''); try { await api(`/owner/orders/${order._id}/status`, { method: 'PATCH', body: { status } }); setActionNotice(`${order.orderNumber} moved to ${status}.`); setRetry(n => n + 1); } catch (error) { setState(current => ({ ...current, actionError: error.message })); } finally { setPendingId(''); } }
  if (state.error) return <section className="page"><RequestError error={state.error.message} retry={() => setRetry(n => n + 1)}/></section>;
  return <section className="page owner-page"><div className="section-heading"><div><p className="eyebrow">Owner workspace</p><h1>{archived ? 'Archived orders' : 'Pickup orders'}</h1></div><button className="secondary" onClick={() => setSearchParams(archived ? {} : { view: 'archived' })}>{archived ? 'Recent orders' : 'View archived'}</button></div><p>Orders are sorted by pickup time. Recent orders stay here for 30 days.</p>{actionNotice && <Notice>{actionNotice}</Notice>}{state.actionError && <Notice error>{state.actionError}</Notice>}{state.loading ? <div className="state-panel">Loading orders…</div> : !state.orders.length ? <div className="state-panel"><h2>{archived ? 'No archived orders' : 'No pickup orders yet'}</h2><p>New customer orders will appear here.</p></div> : <div className="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Pickup</th><th>Items</th><th>Total due</th><th>Status</th><th>Action</th></tr></thead><tbody>{state.orders.map(order => <tr key={order._id}><td><Link to={`/owner/orders/${order._id}`}>{order.orderNumber}</Link></td><td>{order.customerName}<small>{order.phone}</small></td><td>{dateLabel(order.pickupAt, state.timezone)}<small>{timeLabel(order.pickupAt, state.timezone)}</small></td><td>{order.items.reduce((sum, item) => sum + item.quantity, 0)}</td><td>{money(order.total)}</td><td><span className={`status status-${order.status.toLowerCase().replace(' ', '-')}`}>{order.status}</span></td><td>{order.status === 'New' ? <button className="small-button" disabled={pendingId === order._id} onClick={() => advance(order, 'Ready')}>{pendingId === order._id ? 'Updating…' : 'Mark ready'}</button> : order.status === 'Ready' ? <button className="small-button" disabled={pendingId === order._id} onClick={() => advance(order, 'Picked up')}>{pendingId === order._id ? 'Updating…' : 'Mark picked up'}</button> : '—'}</td></tr>)}</tbody></table></div>}</section>;
}
function OwnerOrderDetail() {
  const { orderId } = useParams(); const [order, setOrder] = useState(null); const [error, setError] = useState(''); const [retry, setRetry] = useState(0); const [pending, setPending] = useState(false);
  const [timezone, setTimezone] = useState('Africa/Cairo');
  useEffect(() => { let active = true; setOrder(null); api(`/owner/orders/${orderId}`).then(data => { if (active) { setOrder(data.order); setTimezone(data.timezone); } }).catch(failure => { if (active) setError(failure.message); }); return () => { active = false; }; }, [orderId, retry]);
  async function advance(status) { setPending(true); setError(''); try { const data = await api(`/owner/orders/${orderId}/status`, { method: 'PATCH', body: { status } }); setOrder(data.order); } catch (failure) { setError(failure.message); } finally { setPending(false); } }
  if (error && !order) return error.includes('not found') ? <NotFound/> : <section className="page"><RequestError error={error} retry={() => setRetry(n => n + 1)}/></section>;
  if (!order) return <div className="page"><Notice>Loading order…</Notice></div>;
  return <section className="page detail-page"><Link className="back-link" to="/owner/orders">Back to orders</Link><p className="eyebrow">Order detail</p><h1>{order.orderNumber}</h1>{error && <Notice error>{error}</Notice>}<div className="detail-columns"><div className="summary-panel"><h2>Pickup</h2><p>{dateLabel(order.pickupAt, timezone)} at {timeLabel(order.pickupAt, timezone)}</p><p className={`status status-${order.status.toLowerCase().replace(' ', '-')}`}>{order.status}</p><h2>Customer</h2><p>{order.customerName}</p><p><a href={`tel:${order.phone}`}>{order.phone}</a></p><h2>Payment</h2><p>Pay at pickup · {money(order.total)}</p></div><div className="summary-panel"><h2>Order items</h2>{order.items.map(item => <p key={item.productId}>{item.quantity} × {item.name} <strong>{money(item.unitPrice * item.quantity)}</strong></p>)}{order.status === 'Cancelled' ? <Notice>Customer cancelled this order. Stock was restored.</Notice> : order.status === 'New' ? <button disabled={pending} onClick={() => advance('Ready')}>Mark ready</button> : order.status === 'Ready' ? <button disabled={pending} onClick={() => advance('Picked up')}>Mark picked up</button> : <Notice>Order picked up.</Notice>}</div></div></section>;
}
function OwnerProducts() {
  const location = useLocation(); const [state, setState] = useState({ loading: true }); const [retry, setRetry] = useState(0);
  const notice = location.state?.saved ? `${location.state.saved} saved.` : location.state?.restocked ? `${location.state.restocked} now has ${location.state.stock} units in stock.` : '';
  useEffect(() => { let active = true; setState({ loading: true }); api('/owner/products').then(data => { if (active) setState({ products: data.products }); }).catch(error => { if (active) setState({ error }); }); return () => { active = false; }; }, [retry]);
  return <section className="page owner-page"><div className="section-heading"><div><p className="eyebrow">Owner workspace</p><h1>Products</h1></div><Link className="button" to="/owner/products/new">Create product</Link></div>{notice && <Notice>{notice}</Notice>}{state.error ? <RequestError error={state.error.message} retry={() => setRetry(n => n + 1)}/> : state.loading ? <div className="state-panel">Loading products…</div> : !state.products.length ? <div className="state-panel"><h2>Your menu is empty</h2><p>Create a product to put it in the catalog.</p><Link className="button" to="/owner/products/new">Create product</Link></div> : <div className="product-grid owner-products">{state.products.map(product => <article className="product-card" key={product._id}><Link to={`/owner/products/${product._id}/edit`}><ProductPhoto product={product}/><div className="product-info"><div className="product-title"><h2>{product.name}</h2><span>{money(product.price)}</span></div><p>{product.category} · {product.stock} in stock</p><span className={`status ${product.active ? 'status-active' : 'status-archived'}`}>{product.active ? 'Active' : 'Archived'}</span></div></Link><div className="card-action"><Link className="button secondary" to={`/owner/products/${product._id}/edit`}>Edit</Link>{product.active && <Link className="button secondary" to={`/owner/products/${product._id}/restock`}>Restock</Link>}{product.active && <Link className="text-button" to={`/owner/products/${product._id}/archive`}>Archive</Link>}</div></article>)}</div>}</section>;
}
function ProductForm() {
  const { productId } = useParams(); const editing = !!productId; const navigate = useNavigate(); const [product, setProduct] = useState(null); const [error, setError] = useState(''); const [pending, setPending] = useState(false); const [progress, setProgress] = useState(0); const [imageUrl, setImageUrl] = useState(''); const [retry, setRetry] = useState(0);
  useEffect(() => { if (!editing) return; let active = true; api(`/owner/products/${productId}`).then(data => { if (active) { setProduct(data.product); setImageUrl(data.product.imageUrl || ''); } }).catch(failure => { if (active) setError(failure.message); }); return () => { active = false; }; }, [editing, productId, retry]);
  async function onFile(event) { const file = event.target.files?.[0]; if (!file) return; setError(''); if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type) || file.size > 5 * 1024 * 1024) { setError('Choose a JPEG, PNG, or WebP image under 5 MB.'); event.target.value = ''; return; } setProgress(1); try { const result = await upload(file.name, file, { access: 'public', handleUploadUrl: '/api/owner/product-image-upload', onUploadProgress: value => setProgress(Math.round(value.percentage)) }); setImageUrl(result.url); } catch (failure) { setError(failure.message || 'Image upload failed. Try again.'); } finally { setProgress(0); } }
  async function submit(event) { event.preventDefault(); setPending(true); setError(''); const form = new FormData(event.currentTarget); const body = { name: form.get('name'), description: form.get('description'), category: form.get('category'), price: Number(form.get('price')), ...(editing ? {} : { stock: Number(form.get('stock')) }), ...(imageUrl ? { imageUrl } : {}) }; try { const data = await api(editing ? `/owner/products/${productId}` : '/owner/products', { method: editing ? 'PATCH' : 'POST', body }); navigate('/owner/products', { replace: true, state: { saved: data.product.name } }); } catch (failure) { setError(failure.message); } finally { setPending(false); } }
  if (error && editing && !product) return <section className="page"><RequestError error={error} retry={() => setRetry(n => n + 1)}/></section>;
  if (editing && !product) return <div className="page"><Notice>Loading product…</Notice></div>;
  return <section className="page form-page"><Link className="back-link" to="/owner/products">Back to products</Link><p className="eyebrow">Owner workspace</p><h1>{editing ? 'Edit product' : 'Create product'}</h1>{product?.sample && <Notice>This is sample catalog content.</Notice>}{error && <Notice error>{error}</Notice>}<form className="owner-form" onSubmit={submit} aria-busy={pending}><label htmlFor="name">Product name</label><input id="name" name="name" required maxLength="160" defaultValue={product?.name || ''}/><label htmlFor="description">Description</label><textarea id="description" name="description" rows="5" required maxLength="2000" defaultValue={product?.description || ''}/><label htmlFor="category">Category</label><select id="category" name="category" required defaultValue={product?.category || 'Bread'}>{categories.map(category => <option key={category}>{category}</option>)}</select><label htmlFor="price">Price in sample minor units <span className="helper">Currency is not confirmed.</span></label><input id="price" name="price" type="number" min="1" step="1" required defaultValue={product?.price || ''}/>{!editing && <><label htmlFor="stock">Initial stock</label><input id="stock" name="stock" type="number" min="0" step="1" required defaultValue="0"/></>}<label htmlFor="photo">Product photo <span className="helper">JPEG, PNG, or WebP · maximum 5 MB</span></label><input id="photo" type="file" accept="image/jpeg,image/png,image/webp" onChange={onFile}/>{progress > 0 && <div className="upload-progress" role="status">Uploading photo: {progress}%<progress value={progress} max="100"/></div>}{imageUrl && <img className="upload-preview" src={imageUrl} alt="Selected product"/>}<div className="form-actions"><Link className="button secondary" to="/owner/products">Cancel</Link><button disabled={pending || progress > 0}>{pending ? 'Saving…' : editing ? 'Save changes' : 'Create product'}</button></div></form></section>;
}
function ArchiveProduct() {
  const { productId } = useParams(); const navigate = useNavigate(); const [product, setProduct] = useState(null); const [error, setError] = useState(''); const [pending, setPending] = useState(false);
  useEffect(() => { api(`/owner/products/${productId}`).then(data => setProduct(data.product)).catch(failure => setError(failure.message)); }, [productId]);
  async function archive() { setPending(true); setError(''); try { await api(`/owner/products/${productId}/archive`, { method: 'POST' }); navigate('/owner/products', { replace: true }); } catch (failure) { setError(failure.message); setPending(false); } }
  if (error && !product) return <section className="page"><RequestError error={error} retry={() => window.location.reload()}/></section>;
  if (!product) return <div className="page"><Notice>Loading product…</Notice></div>;
  return <section className="page state-panel"><p className="eyebrow">Archive product</p><h1>Remove {product.name} from the menu?</h1><p>Customers won’t be able to see or add this product. Past order details will keep their saved product information.</p>{error && <Notice error>{error}</Notice>}<div className="form-actions"><Link className="button secondary" to="/owner/products">Keep product</Link><button disabled={pending} onClick={archive}>{pending ? 'Archiving…' : 'Archive product'}</button></div></section>;
}
function Restock() {
  const { productId } = useParams(); const navigate = useNavigate(); const [product, setProduct] = useState(null); const [error, setError] = useState(''); const [pending, setPending] = useState(false); const [quantity, setQuantity] = useState('');
  useEffect(() => { api(`/owner/products/${productId}`).then(data => setProduct(data.product)).catch(failure => setError(failure.message)); }, [productId]);
  async function submit(event) { event.preventDefault(); setPending(true); setError(''); try { const data = await api(`/owner/products/${productId}/restock`, { method: 'POST', body: { quantity: Number(quantity) } }); navigate('/owner/products', { replace: true, state: { restocked: data.product.name, stock: data.product.stock } }); } catch (failure) { setError(failure.message); setPending(false); } }
  if (error && !product) return <section className="page"><RequestError error={error} retry={() => window.location.reload()}/></section>;
  if (!product) return <div className="page"><Notice>Loading product…</Notice></div>;
  return <section className="page form-page"><Link className="back-link" to="/owner/products">Back to products</Link><p className="eyebrow">Restock</p><h1>{product.name}</h1><p>Current stock: <strong>{product.stock}</strong></p>{error && <Notice error>{error}</Notice>}<form className="owner-form" onSubmit={submit}><label htmlFor="restock-quantity">Units to add</label><input id="restock-quantity" type="number" min="1" step="1" required value={quantity} onChange={event => setQuantity(event.target.value)}/><div className="form-actions"><Link className="button secondary" to="/owner/products">Cancel</Link><button disabled={pending}>{pending ? 'Updating stock…' : 'Add to stock'}</button></div></form></section>;
}
function OwnerNotFound() { return <section className="page state-panel"><h1>That owner page isn’t here.</h1><p>Return to the order queue.</p><Link className="button" to="/owner/orders">Back to orders</Link></section>; }
function App() {
  return <BrowserRouter><RouteFocus/><Routes><Route element={<CustomerShell/>}><Route index element={<Catalog/>}/><Route path="products/:productId" element={<ProductDetail/>}/><Route path="cart" element={<CartPage/>}/><Route path="checkout" element={<Checkout/>}/><Route path="orders/:orderNumber/confirmation" element={<Confirmation/>}/><Route path="*" element={<NotFound/>}/></Route><Route path="owner/login" element={<SignIn/>}/><Route path="owner" element={<OwnerShell/>}><Route index element={<Navigate to="orders" replace/>}/><Route path="orders" element={<OwnerOrders/>}/><Route path="orders/:orderId" element={<OwnerOrderDetail/>}/><Route path="products" element={<OwnerProducts/>}/><Route path="products/new" element={<ProductForm/>}/><Route path="products/:productId/edit" element={<ProductForm/>}/><Route path="products/:productId/archive" element={<ArchiveProduct/>}/><Route path="products/:productId/restock" element={<Restock/>}/><Route path="*" element={<OwnerNotFound/>}/></Route></Routes></BrowserRouter>;
}
const root = createRoot(document.getElementById('root'));
root.render(<React.StrictMode><App/></React.StrictMode>);
if (import.meta.hot) import.meta.hot.dispose(() => root.unmount());
